version: "3.3"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    user: "1000"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "8006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    user: "1000"